# Generated by Django 5.1.4 on 2024-12-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_assessment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='gpt_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('course_id', 'instructor')},
        ),
    ]
