# Generated by Django 5.1.4 on 2024-12-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_gpt_analysis_alter_feedback_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='gpt_analysis',
            new_name='processed_data',
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedback',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
