# Generated by Django 5.1.4 on 2024-12-13 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_rename_feedback_text_feedback_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='course_id',
            field=models.CharField(default='default_course', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedback',
            name='instructor',
            field=models.CharField(default='Unknown Instructor', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
