# Generated by Django 5.1.4 on 2024-12-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedback_category_alter_feedback_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='feedback_text',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='processed_data',
            new_name='processed_feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='processed',
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='course_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='instructor',
            field=models.CharField(max_length=100),
        ),
    ]
