- name: Debug Working Directory
  run: |
    pwd
    ls -R
- name: Run Migrations and Tests
  working-directory: feedback_system
  env:
    DJANGO_SETTINGS_MODULE: feedback_system.settings
    DATABASE_URL: postgres://django_user:django_pass@localhost:5432/django_db
  run: |
    python manage.py migrate
    python manage.py test
