name: CI/CD Pipeline for Local Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted  # Run on your local self-hosted runner

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_pass
          POSTGRES_DB: django_db
        ports:
          - 5432:5432

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Up Docker
      - name: Set up Docker
        run: |
          docker --version

      # Step 3: Build and Run Docker Container
      - name: Build and run Django app in Docker
        working-directory: feedback_system
        env:
          DATABASE_URL: postgres://django_user:django_pass@localhost:5432/django_db
        run: |
          # Stop and remove existing container if running
          docker stop django-container-local || true
          docker rm django-container-local || true
          
          # Build the Docker image
          docker build -t django-app-local .

          # Run the container
          docker run -d -p 8000:8000 --name django-container-local \
          -e DATABASE_URL=$DATABASE_URL \
          django-app-local

      # Step 4: Verify Application is Running
      - name: Check running containers
        run: docker ps
