name: CI/CD Pipeline for Local Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use your local machine as a runner

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Compose
        run: |
          docker-compose --version

      # Step 3: Pull and Build Containers
      - name: Build and Run Containers
        run: |
          docker-compose down
          docker-compose up --build -d

      # Step 4: Verify Application
      - name: Verify Application
        run: |
          docker ps
          curl --retry 10 --retry-delay 5 http://localhost:8000
