name: CI/CD Pipeline for Django LMS App

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_pass
          POSTGRES_DB: django_db
        ports:
          - 5432:5432

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install Dependencies
      - name: Install dependencies
        working-directory: feedback_system
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Verify Directory for Debugging (Optional Step)
      - name: List files for debugging
        run: |
          echo "Current Directory:"
          pwd
          echo "List of Files:"
          ls -R feedback_system

      # Step 5: Run Migrations and Tests
      - name: Run migrations and tests
        working-directory: feedback_system
        env:
          DJANGO_SETTINGS_MODULE: feedback_system.settings
          DATABASE_URL: postgres://django_user:django_pass@localhost:5432/django_db
        run: |
          python manage.py migrate
          python manage.py test
